### PR TITLE
add close and install callback

### PR DESCRIPTION
**Pull request by cdbean**
Issue #25 

Add callback to clicking actions

### CODE REVIEW

**Comment by cdbean** [comment]
There are a lot of eslint differences... I am using VS Code, do you have an idea how I should configure it to make the code format consistent?

**Comment by patw0929** [comment]
Have no idea about VSCode... maybe that's because you install some auto-format plugin?
By the way, I would like to handle these formatting issue by `preitter` in the future.

**Comment by cdbean** [comment]
I do have `prettier-eslint` plugin. I tried turning that off and using `eslint` only, but the format only becomes worse... Good that you plan to move to `prettier`, so I would not consider the format difference an issue then :)

Any idea on the coverage failure then?

**Comment by cdbean** [comment]
Hi, are you still following up?

**Comment by patw0929** [comment]
I still have no idea about VSCode's formatting feature... Could you solve it or use another editor to implement this PR? Because I think the formatting commits should not be committed in this PR.

**Comment by cdbean** [comment]
Close this one in favor of #27, which removes the format issue

**Pull request closed without merging**
